### ISSUE TITLE
Procedurenummer of -aanduiding en/of status

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/Regels-bij-activiteiten#11]
In het overleg op 1-10-2020 is ingebracht dat ook een procedurenummer of -aanduiding meegegeven moet kunnen worden (optioneel) op het niveau van de gegevenslevering d.w.z. niet per activiteit e.d. Er moet ook op proceduregeselecteerd cq. opgevraagd kunnen worden. Dit zit m.i. nog niet in de API. Waar en hoe zou dit verwerkt moeten worden?  
Ook is ingebracht dat er sprake zou moeten zijn van een "status-gegeven dat overeenkomt met een herkenbare status in de plansoftware", waarop ook geselecteerd kan worden. Zit er m.i. ook nog niet in. Is dit hetzelfde als die procedure-aanduiding?  Zo nee, toevoegen, en waar dan?

**Comment by melsk-r** [comment]
Dit is de 'werkpakketCode' geworden in de resource 'regeltekst.
