### ISSUE TITLE
Omgevingsnormen met normwaarde-locaties opnemen?

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/Regels-bij-activiteiten#13]
Indien in een regeltekst een norm gesteld is dan kunnen de daarvoor geldende normwaarden verschillen binnen het werkingsgebied van de regeltekst. Denk bijvoorbeeld aan maximale bouwhoogten die binnen het ambtsgebied kunnen verschillen. Dergelijke normwaarden hoeven niet in de regeltekst vermeld te worden. Ze staan dan 'in de kaart' en worden in een GIO aangeleverd (in het STOP/TPOD-bestand). Een norm met dergelijke normwaarden en bijbehorende locaties zit nu niet in het informatiemodel en dus niet in de API. Toch lijkt me de locatie van een dergelijke normwaarde relevant voor toepasbare regels. Je wilt toch iets kunnen vragen als 'Bouwt u niet hoger dan 15 meter?' Die '15' is de normwaarde en geldt voor bepaalde plekken in het ambtsgebied. Op andere plekken is het 10, 20 of meer meter. Dus wil je die plekken cq. locaties weten, lijkt me.  
Overigens komt dit in het CimTR niet voor. Vreemd? Of is dit meer iets voor toepasbare regelbeheer dus voor die applicatie?

**Comment by Rkoenders** [comment]
Inderdaad vreemd, maar volgens mij is dit mechanisme (verschillende waardes op verschillende plekken) nog niet ondersteund door TR.

**Comment by melsk-r** [comment]
Dit is vooralsnog buiten scope. T.z.t. moet duidelijk worden of dit zinvol is.
