### ISSUE TITLE
Moet het atribute 'hoogte' wel opgenomen worden?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Regels-bij-activiteiten#16]
In de resource 'locatie' is het attribuut ‘hoogte’ opgenomen. De hoogte is in een aantal coördinatensystemen echter al onderdeel van dat systeem (bijv. EPSG 7415). De vraag is dus of dit attribute echt opgenomen moet worden.

**Comment by Rkoenders** [comment]
Hoogte is hier in mijn ogen sowieso een onzinnig attribuut omdat het gaat om het bedienen van toepasbare regels. Die doen niets met hoogte. Dus wat mij betreft mag ie weg.

**Comment by embronne** [comment]
Mag weg.

**Comment by melsk-r** [comment]
Het attribuut 'hoogte' is niet opgenomen in de yaml specificatie.
