### ISSUE TITLE
Als leverancier wil ik graag een voorbeeldbestand hebben

### ISSUE THREAD

**Issue by ArjanKloosterboer** [VNG-Realisatie/Regels-bij-activiteiten#25]
... zodat ik daarmee kan testen of mijn applicatie dit goed kan verwerken of exporteren.  

Deze vraag is gesteld in het koppelvlak-leveranciersoverleg van 27 januari jl. Bij voorkeur een voorbeeldbestand (van de bestandsuitwisseling o.b.v. de API) voor Gemeentestad, de [STOP/TPOD-voorbeeld-gemeente van Geonovum](https://www.geonovum.nl/geo-standaarden/omgevingswet/STOPTPOD#TPOD). 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
- [ ] referentie-implementatie

**Comment by ArjanKloosterboer** [comment]
Het voorbeeldbestand van Gemeentestad is dit [STOP/TPOD-bestand](https://geonovum.github.io/TPOD-vbb/Voorbeeldbestanden/Vb_Omgevingsplan_Gemeentestad_v1.0.6.zip).  Het is afgeleid van het [IMOW](https://geonovum.github.io/TPOD/CIMOW/IMOW%20v1.0.3.pdf) en [dit zijn de desbetreffende schema's](https://geonovum.github.io/TPOD/CIMOW/IMOW%20v1.0.3.zip).

**Comment by melsk-r** [comment]
De gevraagde voorbeeldbestanden, zowel voor berichten als voor bestandsuitwisseling, vind je [hier](https://github.com/VNG-Realisatie/Regels-bij-activiteiten/tree/main/voorbeelden).
